/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package password_manager;

import java.awt.Color;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author sunnyladdy
 */
public class showcreditcard1 extends javax.swing.JInternalFrame implements mydbvariables {

    /**
     * Creates new form showcreditcard
     */
    public static boolean flag = false,securitypass = false;
    public static String idnumber="";
    public showcreditcard1() {
        initComponents();
        cardnumber.setEchoChar('X');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showingDetailss = new javax.swing.JPanel();
        topcardname = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cardname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        issuingbankname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cardcolor = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        usernote = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sno = new javax.swing.JTextField();
        passwordprotected = new javax.swing.JCheckBox();
        flagvar = new javax.swing.JLabel();
        get = new javax.swing.JButton();
        monthbox = new javax.swing.JComboBox<>();
        yearbox = new javax.swing.JComboBox<>();
        cardnumber = new javax.swing.JPasswordField();
        securitycode = new javax.swing.JPasswordField();
        cardholdername = new javax.swing.JTextField();
        Delete_btn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setClosable(true);
        setTitle("CreditCard");
        getContentPane().setLayout(null);

        showingDetailss.setBackground(new java.awt.Color(255, 255, 255));
        showingDetailss.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showingDetailssMouseMoved(evt);
            }
        });
        showingDetailss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showingDetailssMouseEntered(evt);
            }
        });
        showingDetailss.setLayout(null);

        topcardname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topcardname.setForeground(new java.awt.Color(255, 255, 255));
        topcardname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_manager/images/creditcardicon.png"))); // NOI18N
        topcardname.setText("dsdasdsds");
        showingDetailss.add(topcardname);
        topcardname.setBounds(10, 10, 270, 80);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Card Number");
        showingDetailss.add(jLabel10);
        jLabel10.setBounds(10, 155, 96, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Security Code");
        showingDetailss.add(jLabel11);
        jLabel11.setBounds(10, 193, 96, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Expiration Date");
        showingDetailss.add(jLabel12);
        jLabel12.setBounds(10, 231, 83, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Card HolderName");
        showingDetailss.add(jLabel13);
        jLabel13.setBounds(10, 269, 96, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Name this Card");
        showingDetailss.add(jLabel14);
        jLabel14.setBounds(10, 307, 96, 15);
        showingDetailss.add(cardname);
        cardname.setBounds(124, 307, 146, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Issuing Bank");
        showingDetailss.add(jLabel15);
        jLabel15.setBounds(10, 345, 67, 15);
        showingDetailss.add(issuingbankname);
        issuingbankname.setBounds(124, 345, 146, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Card Color");
        showingDetailss.add(jLabel16);
        jLabel16.setBounds(10, 383, 55, 15);

        cardcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Silver", "White", "Red", "Orange", "Gold", "Black", "Dark Blue", "Green", "Dark Green" }));
        showingDetailss.add(cardcolor);
        cardcolor.setBounds(124, 383, 148, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Note");
        showingDetailss.add(jLabel17);
        jLabel17.setBounds(14, 421, 96, 15);
        showingDetailss.add(usernote);
        usernote.setBounds(124, 421, 148, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_manager/images/creditcardbackground.png"))); // NOI18N
        showingDetailss.add(jLabel18);
        jLabel18.setBounds(0, 0, 300, 100);

        jLabel19.setText("sno");
        showingDetailss.add(jLabel19);
        jLabel19.setBounds(126, 110, 50, 30);
        showingDetailss.add(sno);
        sno.setBounds(180, 110, 91, 30);

        passwordprotected.setText("Password Protected");
        showingDetailss.add(passwordprotected);
        passwordprotected.setBounds(10, 456, 260, 30);

        flagvar.setForeground(new java.awt.Color(255, 255, 255));
        flagvar.setText("false");
        showingDetailss.add(flagvar);
        flagvar.setBounds(16, 110, 50, 20);

        get.setForeground(new java.awt.Color(255, 255, 255));
        get.setText("get");
        get.setBorder(null);
        get.setContentAreaFilled(false);
        showingDetailss.add(get);
        get.setBounds(16, 130, 17, 15);

        monthbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        showingDetailss.add(monthbox);
        monthbox.setBounds(124, 229, 69, 30);

        yearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));
        showingDetailss.add(yearbox);
        yearbox.setBounds(203, 229, 68, 30);
        showingDetailss.add(cardnumber);
        cardnumber.setBounds(124, 155, 147, 30);
        showingDetailss.add(securitycode);
        securitycode.setBounds(124, 193, 147, 30);
        showingDetailss.add(cardholdername);
        cardholdername.setBounds(124, 270, 146, 31);

        getContentPane().add(showingDetailss);
        showingDetailss.setBounds(0, 0, 290, 500);

        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_btn);
        Delete_btn.setBounds(10, 520, 70, 30);

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(195, 520, 80, 30);

        ok.setText("Update");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(120, 520, 70, 30);

        setBounds(0, 0, 306, 595);
    }// </editor-fold>//GEN-END:initComponents

    private void showingDetailssMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseMoved

    }//GEN-LAST:event_showingDetailssMouseMoved

    private void showingDetailssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseEntered

    }//GEN-LAST:event_showingDetailssMouseEntered

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        //DELETE FROM `details` WHERE 1
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                try
                {
                    String query = "DELETE FROM `creditcards` WHERE sno=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(query);
                    mystatement.setString(1, sno.getText());
                    if(mystatement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this, "Deleted Successfully..");
                        dashlane.paymentsbox.doClick();
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is an Error in Deleting the Details Successfully..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
            }
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            //cardholdername.setEchoChar('*');
            //dashlane.showpassin.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verify Your Password Then Click on Delete...");
            flag = true;
            verifypasswordframe obj = new verifypasswordframe();
            obj.idnumber=dashlane.idnumber;
            obj.call(evt.getActionCommand());
            obj.creditcard = true;
            obj.actions = evt.getActionCommand();
            System.out.println("Action Performing : "+evt.getActionCommand());
            //jDesktopPane1.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);
                try
                {
                    String query = "UPDATE `creditcards` SET `cardholdername`=?,`cardname`=?,`cardnumber`=?,`securitycode`=?,`expirydate`=?,`issuingbank`=?,`cardcolor`=?,`note`=?,`passwordprotected`=? WHERE sno=?";
                    //query = "UPDATE `creditcards` SET `cardnumber`=?,`securitycode`=?,`expirydate`=?,`password`=?,`website`=?,`name`=?,`category`=?,`note`=?,`passwordprotected`=? WHERE sno=?";
                    PreparedStatement obj = myconnection.prepareStatement(query);
                    obj.setString(1,cardholdername.getText());
                    obj.setString(2,cardname.getText());
                    obj.setString(3,cardnumber.getText());
                    obj.setString(4,securitycode.getText());
                    obj.setString(5,monthbox.getSelectedItem().toString()+"-"+yearbox.getSelectedItem().toString());
                    obj.setString(6,issuingbankname.getText());
                    //System.out.println("Index Selected By the user : "+cardcolor.getSelectedIndex());
                    obj.setString(7,String.valueOf(cardcolor.getSelectedItem()));
                    obj.setString(8,usernote.getText());
                    if(passwordprotected.isSelected())
                    {
                        obj.setString(9, "true");
                    }
                    else
                    {
                        obj.setString(9, "false");
                    }
                    obj.setString(10,sno.getText());
                    System.out.println("Query : "+obj.toString());
                    if(obj.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this,"Changes Has Been Saved..");
                        this.dispose();
                        dashlane.paymentsbox.doClick();
                        showpass.showpassin.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Error in Saving the Details..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
            }
            showcreditcard1.securitypass = false;
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            showpass.flag = false;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verify Your Password");
            flag = true;
            verifypasswordframe.creditcard = true;
            verifypasswordframe obj = new verifypasswordframe();
            obj.idnumber=dashlane.idnumber;
            //jDesktopPane1.add(obj);
            obj.setVisible(true);
            securitypass = false;
            dashlane.securitypass = false;
            dashlane.flag = false;
            verifypasswordframe.actions=evt.getActionCommand();
            flag = false;
        }
    }//GEN-LAST:event_okActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        dashlane.securitypass = false;
        securitypass = false;
        dashlane.flag = false;
        flag = false;
        verifypasswordframe.creditcard = false;
        //cardholdername.setEchoChar('*');
        //dashlane.showpassin.setVisible(false);
        showpass.showpassin.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Delete_btn;
    public static javax.swing.JComboBox<String> cardcolor;
    public static javax.swing.JTextField cardholdername;
    public static javax.swing.JTextField cardname;
    public static javax.swing.JPasswordField cardnumber;
    public static javax.swing.JLabel flagvar;
    private javax.swing.JButton get;
    public static javax.swing.JTextField issuingbankname;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public static javax.swing.JComboBox<String> monthbox;
    public static javax.swing.JButton ok;
    public static javax.swing.JCheckBox passwordprotected;
    public static javax.swing.JPasswordField securitycode;
    public static javax.swing.JPanel showingDetailss;
    public static javax.swing.JTextField sno;
    public static javax.swing.JLabel topcardname;
    public static javax.swing.JTextField usernote;
    public static javax.swing.JComboBox<String> yearbox;
    // End of variables declaration//GEN-END:variables
}
