/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package password_manager;

import java.awt.*;
import java.util.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author sunnyladdy
 */
public class showpass extends javax.swing.JInternalFrame implements mydbvariables {

    /**
     * Creates new form showpass
     */
    public static boolean flag=false,securitypass=false;
    public static boolean weak=false,strong=false;
    public static String idnumber;
    public showpass() {
        initComponents();
        if(!dashlane.askforpassword.equalsIgnoreCase("false"))
        {
            userpassword.disable();
        }
        serialno.disable();
        try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                try
                {
                    String query = "select * from category_table";
                    PreparedStatement mystatement = myconnection.prepareStatement(query);
                    ResultSet myresult= mystatement.executeQuery();
                    if(myresult.next())
                    {
                        usercategory.removeAllItems();
                        do
                        {   
                            usercategory.addItem(myresult.getString("category"));
                        }
                        while(myresult.next());
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is an Error in Getting all the Categories..");
                    }
                    query = "select * from addedpasscat";
                    mystatement = myconnection.prepareStatement(query);
                    myresult = mystatement.executeQuery();
                    if(myresult.next())
                    {
                        do
                        {
                            usercategory.addItem(myresult.getString("category"));
                        }
                        while(myresult.next());
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showingDetailss = new javax.swing.JPanel();
        websitename = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        useremail = new javax.swing.JTextField();
        showpassin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hidepassin = new javax.swing.JLabel();
        userlogin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        userseclogin = new javax.swing.JTextField();
        userpassword = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userwebsite = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        webname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        usercategory = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        usernote = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        serialno = new javax.swing.JTextField();
        passwordprotected = new javax.swing.JCheckBox();
        flagvar = new javax.swing.JLabel();
        get = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Delete_btn = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(null);

        showingDetailss.setBackground(new java.awt.Color(255, 255, 255));
        showingDetailss.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showingDetailssMouseMoved(evt);
            }
        });
        showingDetailss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showingDetailssMouseEntered(evt);
            }
        });
        showingDetailss.setLayout(null);

        websitename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        websitename.setForeground(new java.awt.Color(255, 255, 255));
        websitename.setText("hello");
        showingDetailss.add(websitename);
        websitename.setBounds(10, 10, 270, 80);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Email");
        showingDetailss.add(jLabel10);
        jLabel10.setBounds(10, 169, 96, 30);
        showingDetailss.add(useremail);
        useremail.setBounds(123, 169, 149, 30);

        showpassin.setText("show");
        showpassin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpassinMouseClicked(evt);
            }
        });
        showingDetailss.add(showpassin);
        showpassin.setBounds(230, 284, 40, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Login");
        showingDetailss.add(jLabel11);
        jLabel11.setBounds(10, 207, 96, 30);

        hidepassin.setText("hide");
        hidepassin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidepassinMouseClicked(evt);
            }
        });
        showingDetailss.add(hidepassin);
        hidepassin.setBounds(230, 284, 40, 30);
        showingDetailss.add(userlogin);
        userlogin.setBounds(123, 207, 149, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Secondry Login");
        showingDetailss.add(jLabel12);
        jLabel12.setBounds(10, 245, 96, 30);
        showingDetailss.add(userseclogin);
        userseclogin.setBounds(124, 245, 148, 30);

        userpassword.setForeground(new java.awt.Color(204, 204, 204));
        userpassword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                userpasswordCaretUpdate(evt);
            }
        });
        userpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userpasswordMouseClicked(evt);
            }
        });
        userpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpasswordActionPerformed(evt);
            }
        });
        userpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userpasswordKeyPressed(evt);
            }
        });
        showingDetailss.add(userpassword);
        userpassword.setBounds(124, 283, 148, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Password");
        showingDetailss.add(jLabel13);
        jLabel13.setBounds(10, 283, 96, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Website");
        showingDetailss.add(jLabel14);
        jLabel14.setBounds(10, 321, 96, 17);
        showingDetailss.add(userwebsite);
        userwebsite.setBounds(124, 321, 148, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Name");
        showingDetailss.add(jLabel15);
        jLabel15.setBounds(10, 359, 35, 17);
        showingDetailss.add(webname);
        webname.setBounds(124, 359, 148, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Category");
        showingDetailss.add(jLabel16);
        jLabel16.setBounds(10, 397, 57, 17);

        usercategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Silver", "White", "Red", "Orange", "Gold", "Black", "Dark Blue", "Green", "Dark Green" }));
        showingDetailss.add(usercategory);
        usercategory.setBounds(124, 397, 148, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Note");
        showingDetailss.add(jLabel17);
        jLabel17.setBounds(14, 435, 96, 17);
        showingDetailss.add(usernote);
        usernote.setBounds(122, 435, 148, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_manager/images/images (2).jpg"))); // NOI18N
        showingDetailss.add(jLabel18);
        jLabel18.setBounds(0, 0, 300, 100);

        jLabel19.setText("sno");
        showingDetailss.add(jLabel19);
        jLabel19.setBounds(120, 120, 50, 30);
        showingDetailss.add(serialno);
        serialno.setBounds(170, 120, 100, 30);

        passwordprotected.setText("Password Protected");
        showingDetailss.add(passwordprotected);
        passwordprotected.setBounds(10, 470, 260, 30);

        flagvar.setForeground(new java.awt.Color(255, 255, 255));
        flagvar.setText("false");
        showingDetailss.add(flagvar);
        flagvar.setBounds(10, 120, 50, 20);

        get.setForeground(new java.awt.Color(255, 255, 255));
        get.setText("get");
        get.setBorder(null);
        get.setContentAreaFilled(false);
        showingDetailss.add(get);
        get.setBounds(10, 140, 17, 15);

        getContentPane().add(showingDetailss);
        showingDetailss.setBounds(0, 0, 300, 509);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));

        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        ok.setText("Update");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Delete_btn)
                .addGap(57, 57, 57)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 509, 312, 50);

        setBounds(0, 0, 304, 593);
    }// </editor-fold>//GEN-END:initComponents

    private void showpassinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpassinMouseClicked
        userpassword.setEchoChar((char)0);
        hidepassin.setVisible(true);
        showpassin.setVisible(false);
    }//GEN-LAST:event_showpassinMouseClicked

    private void hidepassinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepassinMouseClicked
        userpassword.setEchoChar('*');
        hidepassin.setVisible(false);
        showpassin.setVisible(true);
    }//GEN-LAST:event_hidepassinMouseClicked

    private void userpasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_userpasswordCaretUpdate
        if(flagvar.getText().equalsIgnoreCase("true"))
        {
            userpassword.enable();
            userpassword.setForeground(Color.BLACK);
            showpassin.setVisible(true);
            flagvar.setText("false");
        }
    }//GEN-LAST:event_userpasswordCaretUpdate

    private void userpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userpasswordMouseClicked
        if(!dashlane.askforpassword.equalsIgnoreCase("false"))
        {
            flag = true;
            verifypasswordframe obj = new verifypasswordframe();
            obj.idnumber=idnumber;
            //System.out.println("idnumber : "+idnumber);
            //jDesktopPane1.add(obj);
            obj.setVisible(true);
        }
        if(flagvar.getText().equalsIgnoreCase("true"))
        {
            userpassword.enable();
            userpassword.setForeground(Color.BLACK);
            showpassin.setVisible(true);
        }
    }//GEN-LAST:event_userpasswordMouseClicked

    private void userpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userpasswordKeyPressed
        showpassin.setVisible(true);
    }//GEN-LAST:event_userpasswordKeyPressed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        //DELETE FROM `details` WHERE 1
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                try
                {
                    String query = "DELETE FROM `details` WHERE sno=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(query);
                    mystatement.setString(1, serialno.getText());
                    if(mystatement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this, "Deleted Successfully..");
                        dashlane.passbox.doClick();
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is an Error in Deleting the Details Successfully..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
            }
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            hidepassin.setVisible(false);
            userpassword.setEchoChar('*');
            //dashlane.showpassin.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verify Your Password Then Click on Delete...");
            flag = true;
            verifypasswordframe obj = new verifypasswordframe();
            obj.idnumber=idnumber;
            obj.call(evt.getActionCommand());
            obj.actions = evt.getActionCommand();
            System.out.println("Action Performing : "+evt.getActionCommand());
            //jDesktopPane1.add(obj);
            obj.setVisible(true);
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);
                try
                {
                    String query = "UPDATE `details` SET `email`=?,`login`=?,`secondarylogin`=?,`password`=?,`website`=?,`name`=?,`category`=?,`note`=?,`passwordprotected`=? WHERE sno=?";
                    PreparedStatement obj = myconnection.prepareStatement(query);
                    obj.setString(1,useremail.getText());
                    obj.setString(2,userlogin.getText());
                    obj.setString(3,userseclogin.getText());
                    obj.setString(4,userpassword.getText());
                    obj.setString(5,userwebsite.getText());
                    obj.setString(6,webname.getText());
                    System.out.println("Index Selected By the user : "+usercategory.getSelectedIndex());
                    obj.setString(7,String.valueOf(usercategory.getSelectedIndex()+1));
                    obj.setString(8,usernote.getText());
                    obj.setString(10,serialno.getText());
                    if(passwordprotected.isSelected())
                    {
                        obj.setString(9, "true");
                    }
                    else
                    {
                        obj.setString(9, "false");
                    }
                    if(obj.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this,"Changes Has Been Saved..");
                        if(!weak==true)
                        {
                            dashlane.passbox.doClick();
                        }
                        else
                        {
                            dashlane.securitybox.doClick();
                            weak = false;
                            strong = false;
                        }
                        this.dispose();
                        showpass.showpassin.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Error in Saving the Details..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
            }
            showpass.securitypass = false;
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            showpass.flag = false;
            hidepassin.setVisible(false);
            userpassword.setEchoChar('*');
            //dashlane.showpassin.setVisible(false);
            showpass.showpassin.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verify Your Password");
            flag = true;
            verifypasswordframe obj = new verifypasswordframe();
            obj.idnumber=idnumber;
            //jDesktopPane1.add(obj);
            obj.setVisible(true);
            securitypass = false;
            dashlane.securitypass = false;
            dashlane.flag = false;
            verifypasswordframe.actions=evt.getActionCommand();
            flag = false;
        }
    }//GEN-LAST:event_okActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        dashlane.securitypass = false;
        securitypass = false;
        dashlane.flag = false;
        flag = false;
        hidepassin.setVisible(false);
        userpassword.setEchoChar('*');
        //dashlane.showpassin.setVisible(false);
        showpass.showpassin.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void showingDetailssMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseMoved

    }//GEN-LAST:event_showingDetailssMouseMoved

    private void showingDetailssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseEntered

    }//GEN-LAST:event_showingDetailssMouseEntered

    private void userpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpasswordActionPerformed

    }//GEN-LAST:event_userpasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Delete_btn;
    public static javax.swing.JLabel flagvar;
    private javax.swing.JButton get;
    public static javax.swing.JLabel hidepassin;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JButton ok;
    public static javax.swing.JCheckBox passwordprotected;
    public static javax.swing.JTextField serialno;
    public static javax.swing.JPanel showingDetailss;
    public static javax.swing.JLabel showpassin;
    public static javax.swing.JComboBox<String> usercategory;
    public static javax.swing.JTextField useremail;
    public static javax.swing.JTextField userlogin;
    public static javax.swing.JTextField usernote;
    public static javax.swing.JPasswordField userpassword;
    public static javax.swing.JTextField userseclogin;
    public static javax.swing.JTextField userwebsite;
    public static javax.swing.JTextField webname;
    public static javax.swing.JLabel websitename;
    // End of variables declaration//GEN-END:variables
}
