/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package password_manager;

import java.sql.*;
import javax.swing.*;

public class showtaxcard1 extends javax.swing.JInternalFrame implements mydbvariables {

    /**
     * Creates new form showtaxcard1
     */
    public static boolean flag = false,securitypass = false;
    public static String idnumber="";
    public showtaxcard1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showingDetailss = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        topcardname = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        usernote = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        sno = new javax.swing.JTextField();
        passwordprotected = new javax.swing.JCheckBox();
        flagvar = new javax.swing.JLabel();
        get = new javax.swing.JButton();
        cardnumber = new javax.swing.JTextField();
        idcardname = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();

        setClosable(true);
        setTitle("Tax Numbers");
        getContentPane().setLayout(null);

        showingDetailss.setBackground(new java.awt.Color(255, 255, 255));
        showingDetailss.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showingDetailssMouseMoved(evt);
            }
        });
        showingDetailss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showingDetailssMouseEntered(evt);
            }
        });
        showingDetailss.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Card Number");
        showingDetailss.add(jLabel10);
        jLabel10.setBounds(40, 150, 96, 30);

        topcardname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        topcardname.setForeground(new java.awt.Color(255, 255, 255));
        topcardname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_manager/images/taxcardicon.png"))); // NOI18N
        topcardname.setText("dsdasdsds");
        showingDetailss.add(topcardname);
        topcardname.setBounds(10, 10, 380, 90);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Name");
        showingDetailss.add(jLabel11);
        jLabel11.setBounds(40, 193, 96, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Note");
        showingDetailss.add(jLabel17);
        jLabel17.setBounds(40, 240, 96, 30);
        showingDetailss.add(usernote);
        usernote.setBounds(154, 238, 240, 30);

        jLabel18.setBackground(new java.awt.Color(180, 180, 180));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_manager/images/taxcardbackground.png"))); // NOI18N
        showingDetailss.add(jLabel18);
        jLabel18.setBounds(0, 0, 410, 110);

        jLabel19.setText("sno");
        showingDetailss.add(jLabel19);
        jLabel19.setBounds(235, 116, 50, 30);
        showingDetailss.add(sno);
        sno.setBounds(303, 116, 91, 30);

        passwordprotected.setText("Password Protected");
        showingDetailss.add(passwordprotected);
        passwordprotected.setBounds(10, 280, 380, 37);

        flagvar.setForeground(new java.awt.Color(255, 255, 255));
        flagvar.setText("false");
        showingDetailss.add(flagvar);
        flagvar.setBounds(16, 110, 50, 20);

        get.setForeground(new java.awt.Color(255, 255, 255));
        get.setText("get");
        get.setBorder(null);
        get.setContentAreaFilled(false);
        showingDetailss.add(get);
        get.setBounds(16, 130, 17, 15);
        showingDetailss.add(cardnumber);
        cardnumber.setBounds(154, 150, 240, 30);
        showingDetailss.add(idcardname);
        idcardname.setBounds(154, 192, 240, 32);

        getContentPane().add(showingDetailss);
        showingDetailss.setBounds(0, 0, 410, 330);

        ok.setText("Update");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(200, 340, 90, 30);

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(310, 340, 80, 30);

        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_btn);
        Delete_btn.setBounds(10, 340, 80, 30);

        setBounds(0, 0, 419, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void showingDetailssMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseMoved

    }//GEN-LAST:event_showingDetailssMouseMoved

    private void showingDetailssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showingDetailssMouseEntered

    }//GEN-LAST:event_showingDetailssMouseEntered

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        //DELETE FROM `details` WHERE 1
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                try
                {
                    String query = "DELETE FROM `idcards` WHERE sno=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(query);
                    mystatement.setString(1, sno.getText());
                    if(mystatement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this, "Deleted Successfully..");
                        dashlane.idspanelbox.doClick();
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "There is an Error in Deleting the Details Successfully..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error Due to : "+e.getMessage());
            }
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            //cardholdername.setEchoChar('*');
            //dashlane.showpassin.setVisible(false);
        }
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if(securitypass != false)
        {
            try
            {
                Connection myconnection = DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);
                try
                {
                    String query = "UPDATE `idcards` SET `cardname`=?,`cardnumber`=?,`passwordprotected`=?,`note`=? WHERE sno=?";
                    //query = "UPDATE `creditcards` SET `cardnumber`=?,`securitycode`=?,`expirydate`=?,`password`=?,`website`=?,`name`=?,`category`=?,`note`=?,`passwordprotected`=? WHERE sno=?";
                    PreparedStatement obj = myconnection.prepareStatement(query);
                    obj.setString(1,idcardname.getText());
                    obj.setString(2,cardnumber.getText());
                    obj.setString(4, usernote.getText());
                    if(passwordprotected.isSelected())
                    {
                        obj.setString(3, "true");
                    }
                    else
                    {
                        obj.setString(3, "false");
                    }
                    obj.setString(5,sno.getText());
                    //System.out.println("Query : "+obj.toString());
                    if(obj.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(this,"Changes Has Been Saved..");
                        this.dispose();
                        dashlane.idspanelbox.doClick();
                        showpass.showpassin.setVisible(false);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Error in Saving the Details..");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Error Due to : "+e.getMessage());
            }
            showcreditcard1.securitypass = false;
            dashlane.securitypass = false;
            securitypass = false;
            dashlane.flag = false;
            showpass.flag = false;
        }
    }//GEN-LAST:event_okActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        dashlane.securitypass = false;
        securitypass = false;
        dashlane.flag = false;
        flag = false;
        verifypasswordframe.taxcard = false;
        //cardholdername.setEchoChar('*');
        //dashlane.showpassin.setVisible(false);
        showpass.showpassin.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Delete_btn;
    public static javax.swing.JTextField cardnumber;
    public static javax.swing.JLabel flagvar;
    private javax.swing.JButton get;
    public static javax.swing.JTextField idcardname;
    public static javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public static javax.swing.JButton ok;
    public static javax.swing.JCheckBox passwordprotected;
    public static javax.swing.JPanel showingDetailss;
    public static javax.swing.JTextField sno;
    public static javax.swing.JLabel topcardname;
    public static javax.swing.JTextField usernote;
    // End of variables declaration//GEN-END:variables
}
